icon: ':material-database:'

cit:
  mode: port
  port: 5432

build:
  variants:
    - tag: "14"
      args:
        PG_VERSION: "14"
        BASE_VERSION: "15-quarterly"
      aliases: ["14-pkg"]
    - tag: "14-pkg-latest"
      args:
        PG_VERSION: "14"
        BASE_VERSION: "15"
    - tag: "17"
      args:
        PG_VERSION: "17"
        BASE_VERSION: "15-quarterly"
      aliases: ["17-pkg", "pkg", "latest"]
    - tag: "17-pkg-latest"
      args:
        PG_VERSION: "17"
        BASE_VERSION: "15"
      aliases: ["pkg-latest"]
